version: '2'
services:
  redis:
    image: redis:3.2.8
    ports:
      - "6379:6379"
    container_name: redis
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  airflow_server:
    image: keajer/airflow:latest
    environment:
      TYPE: web_server
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      POSTGRES_PWD: airflow
      WEBSERVER_HOST_NAME: 127.0.0.1:8080
    volumes:
      - ./airflow-dags:/usr/local/airflow/dags
    ports:
     - "8080:8080"
    restart: always
    depends_on:
      - postgres
      - redis
  airflow_scheduler:
    image: keajer/airflow:latest
    environment:
      TYPE: scheduler
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      WEBSERVER_HOST_NAME: 127.0.0.1:8080
      POSTGRES_PWD: airflow
    restart: always
    volumes:
      - ./airflow-dags:/usr/local/airflow/dags
    depends_on:
      - postgres
      - redis
      - airflow_server
  airflow_worker:
    image: keajer/airflow:latest
    environment:
      TYPE: worker
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      POSTGRES_PWD: airflow
      WEBSERVER_HOST_NAME: 127.0.0.1:8080
    ports:
      - "8793:8793"
      - "4040:4040"
    restart: always
    depends_on:
      - postgres
      - redis
      - airflow_server
  airflow_flower:
    image: keajer/airflow:latest
    environment:
      TYPE: flower
      POSTGRES_HOST: postgres
      POSTGRES_PWD: airflow
      REDIS_HOST: redis
      WEBSERVER_HOST_NAME: 127.0.0.1:8080
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      - postgres
      - redis
      - airflow_server
